module.exports = [
    { label: 'Recursive Delete', pattern: '/rm -rf .*/i' },
    { label: 'Force Delete', pattern: '/rm -f .*/i' },
    { label: 'Find & Delete', pattern: '/find .* -delete/i' },
    { label: 'Fork Bomb', pattern: '/:().*{.*:\|:&.*};:/i' },
    { label: 'Wipe Disk (dd)', pattern: '/dd if=\\/dev\\/zero of=\\/dev\\/sd.*/i' },
    { label: 'Wipe Disk (shred)', pattern: '/shred -u .*/i' },
    { label: 'Full Permissions', pattern: '/chmod -R 777 .*/i' },
    { label: 'Own to Root', pattern: '/chown root:root .*/i' },
    { label: 'Format Partition', pattern: '/mkfs\\..* \\/dev\\/.*/i' },
    { label: 'Redirect to Device', pattern: '/.* > \\/dev\\/sd.*/i' },
    { label: 'Execute Remote Script', pattern: '/(curl|wget).*\\|.*(sh|bash|zsh)/i' },
    { label: 'Stop Firewall', pattern: '/systemctl stop (ufw|iptables|firewalld)/i' },
    { label: 'Disable Firewall', pattern: '/ufw disable/i' },
    { label: 'Clear Logs', pattern: '/rm -rf \\/var\\/log\\/*.*/i' },
    { label: 'Kill All Processes', pattern: '/killall -9 .*/i' },
    { label: 'Purge Package', pattern: '/apt-get purge .*/i' },
    { label: 'Windows Force Delete', pattern: '/del \\/f \\/s \\/q .*/i' },
    { label: 'Windows Wipe Directory', pattern: '/rd \\/s \\/q .*/i' },
    { label: 'Windows Format', pattern: '/format [a-z]:/i' },
    { label: 'PowerShell IEX', pattern: '/iex.*(New-Object|DownloadString)/i' },
    { label: 'Git Force Push', pattern: '/git push .* --force/i' },
    { label: 'Git Hard Reset', pattern: '/git reset --hard .*/i' },
    { label: 'SQL Drop Table', pattern: '/DROP TABLE .*/i' },
    { label: 'SQL Truncate', pattern: '/TRUNCATE TABLE .*/i' },
    { label: 'Bash Overwrite Root', pattern: '/.* > \\/etc\\/passwd/i' },
    { label: 'Shadow File Access', pattern: '/cat \\/etc\\/shadow/i' }
];
