module.exports = [
    // === Linux / macOS Destructive ===
    { label: 'Recursive Delete', pattern: '/rm -rf .*/i' },
    { label: 'Force Delete', pattern: '/rm -f .*/i' },
    { label: 'Find & Delete', pattern: '/find .* -delete/i' },
    { label: 'Fork Bomb', pattern: '/:().*{.*:\\|:&.*};:/i' },
    { label: 'Wipe Disk (dd)', pattern: '/dd if=\\/dev\\/zero of=\\/dev\\/sd.*/i' },
    { label: 'Wipe Disk (shred)', pattern: '/shred -u .*/i' },
    { label: 'Full Permissions', pattern: '/chmod -R 777 .*/i' },
    { label: 'Own to Root', pattern: '/chown root:root .*/i' },
    { label: 'Format Partition', pattern: '/mkfs\\..* \\/dev\\/.*/i' },
    { label: 'Redirect to Device', pattern: '/.* > \\/dev\\/sd.*/i' },
    { label: 'Execute Remote Script', pattern: '/(curl|wget).*\\|.*(sh|bash|zsh)/i' },
    { label: 'Stop Firewall', pattern: '/systemctl stop (ufw|iptables|firewalld)/i' },
    { label: 'Disable Firewall', pattern: '/ufw disable/i' },
    { label: 'Clear Logs', pattern: '/rm -rf \\/var\\/log\\/.*/i' },
    { label: 'Kill All Processes', pattern: '/killall -9 .*/i' },
    { label: 'Purge Package', pattern: '/apt-get purge .*/i' },
    { label: 'Overwrite passwd', pattern: '/.* > \\/etc\\/passwd/i' },
    { label: 'Shadow File Access', pattern: '/cat \\/etc\\/shadow/i' },
    { label: 'Crontab Remove', pattern: '/crontab -r/i' },
    { label: 'Systemctl Mask', pattern: '/systemctl mask .*/i' },
    { label: 'SSH Key Inject', pattern: '/echo .* >> .*authorized_keys/i' },
    { label: 'History Clear', pattern: '/history -c/i' },
    { label: 'Reverse Shell', pattern: '/bash -i >& \\/dev\\/tcp\\/.*/i' },
    { label: 'Netcat Backdoor', pattern: '/nc -e \\/bin\\/(ba)?sh .*/i' },
    { label: 'Python Rev Shell', pattern: '/python.*socket.*connect/i' },
    { label: 'Sudoers Edit', pattern: '/echo .* >> \\/etc\\/sudoers/i' },
    { label: 'Mount /dev/sda', pattern: '/mount \\/dev\\/sd.*/i' },
    { label: 'Swap Off', pattern: '/swapoff -a/i' },

    // === Windows Destructive ===
    { label: 'Windows Force Delete', pattern: '/del \\/f \\/s \\/q .*/i' },
    { label: 'Windows Wipe Directory', pattern: '/rd \\/s \\/q .*/i' },
    { label: 'Windows Format', pattern: '/format [a-z]:/i' },
    { label: 'PowerShell IEX', pattern: '/iex.*(New-Object|DownloadString)/i' },
    { label: 'Registry Delete', pattern: '/reg delete .*/i' },
    { label: 'Disable Windows Defender', pattern: '/Set-MpPreference.*-DisableRealtimeMonitoring/i' },
    { label: 'Stop Windows Update', pattern: '/net stop wuauserv/i' },
    { label: 'bcdedit Modify', pattern: '/bcdedit \\/(set|delete) .*/i' },
    { label: 'Cipher Wipe', pattern: '/cipher \\/w:.*/i' },
    { label: 'WMIC Process Kill', pattern: '/wmic process .* delete/i' },
    { label: 'Schtasks Delete', pattern: '/schtasks \\/delete .*/i' },
    { label: 'PowerShell RemoveItem', pattern: '/Remove-Item .* -Recurse -Force/i' },

    // === Git Destructive ===
    { label: 'Git Force Push', pattern: '/git push .* --force/i' },
    { label: 'Git Hard Reset', pattern: '/git reset --hard .*/i' },
    { label: 'Git Clean Force', pattern: '/git clean -fdx/i' },
    { label: 'Git Branch Delete', pattern: '/git branch -D .*/i' },
    { label: 'Git Remote Reset', pattern: '/git push origin --delete .*/i' },

    // === Database Destructive ===
    { label: 'SQL Drop Table', pattern: '/DROP TABLE .*/i' },
    { label: 'SQL Truncate', pattern: '/TRUNCATE TABLE .*/i' },
    { label: 'SQL Drop Database', pattern: '/DROP DATABASE .*/i' },
    { label: 'SQL Delete All', pattern: '/DELETE FROM .* WHERE 1/i' },
    { label: 'MongoDB Drop', pattern: '/db\\..*\\.drop\\(/i' },
    { label: 'Redis FlushAll', pattern: '/FLUSHALL/i' },

    // === Docker / Container ===
    { label: 'Docker System Prune', pattern: '/docker system prune -a/i' },
    { label: 'Docker Remove All', pattern: '/docker rm -f \\$\\(docker ps -aq\\)/i' },
    { label: 'Docker Image Prune', pattern: '/docker image prune -a/i' },
    { label: 'Kubectl Delete All', pattern: '/kubectl delete .* --all/i' },

    // === NPM / Node ===
    { label: 'NPM Cache Clean Force', pattern: '/npm cache clean --force/i' },
    { label: 'NPX Dangerous Script', pattern: '/npx .*(rimraf|del-cli) \\//i' },
    { label: 'Node Eval Dangerous', pattern: '/node -e.*require\\(.*child_process/i' },
];
